FROM docker.io/bhgrant/hackoregon_geodjango
ENV PYTHONUNBUFFERED 1
EXPOSE 8000

WORKDIR /code
COPY /bin/requirements.txt /code/
RUN pip install -r requirements.txt
RUN python
COPY . /code/
ENTRYPOINT [ "/code/bin/local-docker-entrypoint.sh" ]