version: '3.4'
services:
  db_development:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    image: db_development
    ports:
      - 5439:5432
    environment:
      - POSTGRES_PASSWORD
  api_development:
    build:
      context: .
      dockerfile: DOCKERFILE.api
    image: api
    command: ./bin/local-docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db_development
    environment:
      - PROJECT_NAME
      - DEBUG
      - POSTGRES_USER
      - POSTGRES_NAME
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PASSWORD
      - DJANGO_SECRET_KEY
