version: '3.4'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/znmeb/odot_crash_data
    environment:
      - POSTGRES_PASSWORD
    ports: 
      - 5439:5432
    env_file: ./bin/.env
  api:
    environment:
    - DEBUG=${DEBUG}
    - PROJECT_NAME=${PROJECT_NAME}
    build:
      context: .
      dockerfile: DOCKERFILE
    image: "${API_DOCKER_IMAGE}"
    command: ./bin/local-docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: ./bin/.env