FROM docker.io/znmeb/postgis
LABEL maintainer="M. Edward (Ed) Borasky <znmeb@znmeb.net>"

WORKDIR /
RUN mkdir -p /docker-entrypoint-initdb.d/
COPY /bin/odot_crash_data.sql /docker-entrypoint-initdb.d/